export const REQUIRED_ACTIONS = {
  NONE: 'NONE',
  RE_LOGIN: 'RE_LOGIN',
  REFRESH_TOKEN: 'REFRESH_TOKEN',
  MFA_AUTH: 'MFA_AUTH',
  RETRY: 'RETRY',
  RETRY_LATER: 'RETRY_LATER',
  CONTACT_SUPPORT: 'CONTACT_SUPPORT',
};
